import asyncio
import os
import json
from contextlib import asynccontextmanager, suppress
from pathlib import Path
from datetime import date
from fastapi import FastAPI, Depends, Request, HTTPException
from sqlalchemy import text
from fastapi.responses import FileResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from app.db import engine, get_db, SessionLocal, Base
from app.auth import WebUser, WebSession, get_user, require, MODULES, hash_password
from app.config import settings
from app.models import MasterOption, WbHeaderAlias
from app.routers import health, masters, production, hsd, reconciliation, dashboard, shift_control, webapp, sites, site_ops, maintenance
from app.services.wb_mapping import ensure_wb_header_mapping
from app.services.attendance_automation import automation_loop
from app.site_models import create_multisite_tables
from app.maintenance_models import create_maintenance_tables
from app.services.site_context import seed_default_sites_and_shifts
from app.services.cloud_sync import init_sync_source
from app.services.tiom_reference_seed import seed_tiom_temp_reference_data
from app.services.tiom_location_erp import ensure_location_master_schema, ensure_location_master_roles, ensure_tiom_route_master_schema, ensure_tiom_routes_from_history


def _zero_tiom_hsd_test_data(db):
    """One-time zeroing of TEMP TIOM HSD transactional values.

    Tanker/equipment masters are untouched. Existing test rows remain only as
    inert audit history, while all quantities and meter-derived values become
    zero/blank so new testing starts from a clean opening balance.
    """
    sync_exists = bool(db.execute(text("SELECT to_regclass('public.sync_change_log')")).scalar())
    sync_before = int(db.execute(text(
        "SELECT COALESCE(MAX(change_id),0) FROM sync_change_log"
    )).scalar() or 0) if sync_exists else 0

    statements = [
        "UPDATE hsd_issue_allocation SET litres=0, amount=0",
        "UPDATE tiom_hsd_issue_detail SET previous_meter_reading=NULL, usage=NULL, efficiency=NULL, efficiency_unit=NULL",
        "UPDATE tiom_hsd_stock_check SET book_litres=0, physical_litres=0, variance_litres=0",
        "UPDATE hsd_issue SET litres=0, amount=0, meter_reading=NULL",
        "UPDATE tiom_hsd_receipt_detail SET discount_per_l=0, net_amount=0",
        "UPDATE hsd_purchase_lot SET litres_received=0, litres_remaining=0, amount=0",
    ]
    counts = {}
    for sql in statements:
        result = db.execute(text(sql))
        counts[sql.split()[1]] = int(result.rowcount or 0)

    # The temp reset must never be replayed into the PC replica. Mark only the
    # sync records generated by this reset as internal reset events; normal
    # business changes keep their original I/U/D operation.
    if sync_exists:
        db.execute(text("""
            UPDATE sync_change_log
               SET operation='R'
             WHERE change_id > :before_id
               AND table_name IN (
                 'hsd_issue_allocation','tiom_hsd_issue_detail',
                 'tiom_hsd_stock_check','hsd_issue',
                 'tiom_hsd_receipt_detail','hsd_purchase_lot'
               )
        """), {"before_id": sync_before})

    db.commit()
    verify = db.execute(text("""
        SELECT
          COALESCE((SELECT SUM(litres_received) FROM hsd_purchase_lot),0) AS received,
          COALESCE((SELECT SUM(litres_remaining) FROM hsd_purchase_lot),0) AS available,
          COALESCE((SELECT SUM(litres) FROM hsd_issue),0) AS issued,
          COALESCE((SELECT COUNT(*) FROM hsd_issue WHERE meter_reading IS NOT NULL),0) AS meter_rows,
          COALESCE((SELECT SUM(physical_litres) FROM tiom_hsd_stock_check),0) AS physical
    """)).mappings().one()
    return {"updatedRows": counts, "verification": {k: float(v) for k,v in verify.items()}}


@asynccontextmanager
async def lifespan(app):
    # Fresh database safety: create the complete registered core schema first so
    # all FK targets (persons/equipment/locations/products/etc.) exist before
    # multisite and maintenance extension tables are created.
    Base.metadata.create_all(engine, checkfirst=True)
    # Older PC/temp databases predate Location.role. Add it before any ORM query
    # so Source/Destination/Both lives in the central Location Master.
    ensure_location_master_schema(engine)
    ensure_tiom_route_master_schema(engine)
    create_multisite_tables(engine)
    create_maintenance_tables(engine)
    init_sync_source(engine)
    # Pilot migration safety: if an older build left exactly one active account
    # with no management/modules, treat it as the original local administrator.
    # Never auto-promote when multiple accounts exist.
    with SessionLocal() as db:
        ensure_wb_header_mapping(db)
        ensure_location_master_roles(db)
        ensure_tiom_routes_from_history(db)
        seed_default_sites_and_shifts(db)
        if os.getenv("TIOM_TEMP_HSD_ZERO_ONCE", "").strip().lower() in {"1","true","yes","on"}:
            reset_result=_zero_tiom_hsd_test_data(db)
            print("TIOM_TEMP_HSD_ZERO_OK="+json.dumps(reset_result,sort_keys=True),flush=True)
        if os.getenv("TIOM_TEMP_REFERENCE_SEED", "").strip().lower() in {"1","true","yes","on"}:
            seed_counts=seed_tiom_temp_reference_data(db)
            print("TIOM_TEMP_REFERENCE_SEED_OK="+json.dumps(seed_counts,sort_keys=True),flush=True)
        users = db.query(WebUser).all()
        # Cloud test bootstrap: create the first administrator only when the database
        # is empty and explicit Render environment variables are provided. No
        # credentials are stored in source control.
        if not users:
            bootstrap_login = os.getenv('NMTPL_BOOTSTRAP_ADMIN_LOGIN', '').strip().lower()
            bootstrap_password = os.getenv('NMTPL_BOOTSTRAP_ADMIN_PASSWORD', '')
            bootstrap_name = os.getenv('NMTPL_BOOTSTRAP_ADMIN_NAME', 'Administrator').strip() or 'Administrator'
            if bootstrap_login and bootstrap_password:
                db.add(WebUser(
                    login_id=bootstrap_login,
                    name=bootstrap_name,
                    password_hash=hash_password(bootstrap_password),
                    modules=','.join(sorted(MODULES)),
                    shifts='ALL',
                    admin=True,
                    active=True,
                ))
                db.flush()
                users = db.query(WebUser).all()
        if len(users) == 1:
            u = users[0]
            if u.active and not u.admin and not (u.modules or '').strip():
                u.admin = True
                u.modules = ','.join(sorted(MODULES))
                u.shifts = 'ALL'
        db.commit()
        diag_date=os.getenv("TIOM_TEMP_DIAG_DATE", "").strip()
        if diag_date:
            admin_user=next((x for x in users if x.active and x.admin),None)
            if not admin_user:
                raise RuntimeError("TIOM temp diagnostic requires an active admin user.")
            dash=webapp.dashboard_desk(db,admin_user,{"mode":"TODAY","toDate":diag_date,"shift":"ALL"})
            dk=dash.get("kpis",{})
            prod_diag={
                "date":diag_date,
                "kpis":{k:dk.get(k) for k in (
                    "wbTrips","wbTonnes","avgPayload","fieldTrips","matched","likely",
                    "wbUnmatched","tripNoWb","matchRate","misReports","misTrips",
                    "misOperationalQty","misObTrips","misObQty","misRomTrips","misRomQty",
                    "romInputMt","finalProductionMt","finalRecoveryPct","oldStockExcludedMt",
                    "crusherFeed","screenFeed","hsdLitres","hsdPerTonne"
                )},
                "production":dash.get("production"),
                "productionMaterials":dash.get("productionMaterials"),
                "plantPerformance":dash.get("plantPerformance"),
                "exceptions":dash.get("exceptions"),
                "shiftComparison":dash.get("shiftComparison"),
            }
            print("TIOM_TEMP_DIAG_PRODUCTION="+json.dumps(prod_diag,sort_keys=True,default=str),flush=True)

            hsd_diag={"date":diag_date,"shifts":{}}
            for sh in ("A","B","C"):
                desk=webapp.tiom_hsd_desk(db,admin_user,{
                    "date":diag_date,"shift":sh,"reportFrom":diag_date,"reportTo":diag_date
                })
                hsd_diag["shifts"][sh]={
                    "entrySummary":desk.get("entrySummary"),
                    "recentIssues":desk.get("recentIssues"),
                    "stockChecks":desk.get("stockChecks"),
                    "tankers":desk.get("tankers"),
                }
            hsd_diag["issues"]= [
                dict(r) for r in db.execute(text("""
                    SELECT i.shift,i.machine_id,i.tanker_id,i.litres,i.meter_type,
                           i.meter_reading,i.reference,i.issued_at,
                           d.previous_meter_reading,d.usage,d.efficiency,d.efficiency_unit,d.entered_by
                    FROM hsd_issue i
                    LEFT JOIN tiom_hsd_issue_detail d ON d.issue_id=i.issue_id
                    WHERE i.operating_date=CAST(:d AS date)
                    ORDER BY i.issued_at
                """),{"d":diag_date}).mappings().all()
            ]
            hsd_diag["receipts"]=[
                dict(r) for r in db.execute(text("""
                    SELECT d.operating_date,d.shift,d.receipt_type,l.tanker_id,
                           l.litres_received,l.litres_remaining,l.rate_per_l,l.amount,
                           l.received_at,l.supplier,l.invoice_no,d.discount_per_l,d.net_amount,
                           d.remarks,d.entered_by
                    FROM hsd_purchase_lot l
                    LEFT JOIN tiom_hsd_receipt_detail d ON d.lot_id=l.lot_id
                    WHERE d.operating_date=CAST(:d AS date)
                    ORDER BY l.received_at
                """),{"d":diag_date}).mappings().all()
            ]
            hsd_diag["stockChecks"]=[
                dict(r) for r in db.execute(text("""
                    SELECT shift,tanker_id,checked_at,book_litres,physical_litres,
                           variance_litres,remarks,entered_by
                    FROM tiom_hsd_stock_check
                    WHERE operating_date=CAST(:d AS date)
                    ORDER BY checked_at
                """),{"d":diag_date}).mappings().all()
            ]
            print("TIOM_TEMP_DIAG_HSD="+json.dumps(hsd_diag,sort_keys=True,default=str),flush=True)

            raw_diag={
                "productionReports":[dict(r) for r in db.execute(text("""
                    SELECT report_id,shift,status,remarks,entered_by,entered_at,submitted_by,submitted_at,version
                    FROM tiom_shift_production_report
                    WHERE operating_date=CAST(:d AS date)
                    ORDER BY CASE shift WHEN 'A' THEN 1 WHEN 'B' THEN 2 WHEN 'C' THEN 3 ELSE 9 END
                """),{"d":diag_date}).mappings().all()],
                "productionMovements":[dict(r) for r in db.execute(text("""
                    SELECT h.shift,h.status,m.row_no,m.movement_code,
                           m.source_location_id,m.destination_location_id,
                           m.trips,m.qty_mt,m.remarks,m.entered_at
                    FROM tiom_shift_production_movement m
                    JOIN tiom_shift_production_report h ON h.report_id=m.report_id
                    WHERE h.operating_date=CAST(:d AS date)
                    ORDER BY CASE h.shift WHEN 'A' THEN 1 WHEN 'B' THEN 2 WHEN 'C' THEN 3 ELSE 9 END,m.row_no
                """),{"d":diag_date}).mappings().all()],
                "productionCalculated":{
                    sh:webapp._tiom_shift_report_data(db,date.fromisoformat(diag_date),sh,True)
                    for sh in ("A","B","C")
                },
                "wbBatches":[dict(r) for r in db.execute(text("""
                    SELECT shift,status,COUNT(*) AS batches,
                           MAX(confirmed_at) AS latest_confirmed
                    FROM wb_import_batch
                    WHERE operating_date=CAST(:d AS date)
                    GROUP BY shift,status ORDER BY shift,status
                """),{"d":diag_date}).mappings().all()],
                "wbMaterials":[dict(r) for r in db.execute(text("""
                    SELECT b.shift,COALESCE(w.material_name,w.material_code,'Unmapped') AS material,
                           COUNT(*) AS trips,ROUND(SUM(COALESCE(w.net_kg,0))/1000.0,2) AS tonnes
                    FROM wb_movement w
                    JOIN wb_import_batch b ON b.batch_id=w.batch_id
                    WHERE b.operating_date=CAST(:d AS date)
                      AND b.status='CONFIRMED'
                      AND w.row_status='VALID'
                    GROUP BY b.shift,COALESCE(w.material_name,w.material_code,'Unmapped')
                    ORDER BY b.shift,tonnes DESC
                """),{"d":diag_date}).mappings().all()],
            }
            print("TIOM_TEMP_DIAG_RAW="+json.dumps(raw_diag,sort_keys=True,default=str),flush=True)
        if os.getenv("TIOM_TEMP_SELFTEST", "").strip().lower() in {"1","true","yes","on"}:
            admin_user=next((x for x in users if x.active and x.admin),None)
            if not admin_user:
                raise RuntimeError("TIOM temp self-test requires an active admin user.")
            mis_test=webapp.tiom_mis_desk(db,admin_user,{})
            dash_test=webapp.dashboard_desk(db,admin_user,{"mode":"TODAY","shift":"ALL"})
            expected_activities={"STACKING","DRILL FACE","TWIN HOPPER CLEANING","QDS","DISPATCH"}
            activity_ids={x.get("id") for x in mis_test.get("activities",[])}
            machine_ids={x.get("id") for x in mis_test.get("deploymentMachines",[])}
            trip_machines=mis_test.get("machines",[])
            required_machines={"DOZER D8-1","DOZER D8-2","DOZER D6-3","DOZER D6-4","GRADER-01","GRADER-02","01.HITACHI-210 (DRILL)","02.HITACHI-210 (DRILL)-2"}
            kpis=dash_test.get("kpis",{})
            production_source_ids={x.get("id") for x in mis_test.get("sourceLocations",[])}
            production_destination_ids={x.get("id") for x in mis_test.get("destinationLocations",[])}
            dashboard_source_ids={x.get("id") for x in dash_test.get("availableSources",[])}
            dashboard_destination_ids={x.get("id") for x in dash_test.get("availableDestinations",[])}
            checks={
                "activitiesVisible":expected_activities.issubset(activity_ids),
                "machinesVisible":required_machines.issubset(machine_ids),
                "tripMachinesLoadingOnly":all(x.get("group")=="LOADING" for x in trip_machines),
                "leadRulesVisible":len(mis_test.get("leadRules",[])),
                "leadDashboardKeys":all(x in kpis for x in ("leadResolvedTrips","leadMissingTrips","leadWithWbTrips","leadWithoutWbTrips","avgLeadKm","leadTonKm")),
                "sevenDayCumulative":all("cumulativeTonnes" in x and "cumulativeLeadTonKm" in x for x in dash_test.get("sevenDay",[])),
                "monthCumulative":all("cumulativeTonnes" in x for x in dash_test.get("monthTrend",[])),
                "sourceMasterConsistent":production_source_ids==dashboard_source_ids and len(production_source_ids)>=5,
                "destinationMasterConsistent":production_destination_ids==dashboard_destination_ids and len(production_destination_ids)>=29,
                "dashboardUsesCanonicalFilters":all(isinstance(x,dict) and x.get("id") and x.get("label") for x in dash_test.get("availableSources",[])+dash_test.get("availableDestinations",[])),
            }
            if not all(v is True or (k=="leadRulesVisible" and int(v)>=276) for k,v in checks.items()):
                raise RuntimeError("TIOM temp self-test failed: "+json.dumps(checks,sort_keys=True))
            print("TIOM_TEMP_SELFTEST_OK="+json.dumps(checks,sort_keys=True),flush=True)

    attendance_task = asyncio.create_task(automation_loop(), name="attendance-auto-close")
    cloud_automation_task = asyncio.create_task(automation.automation_loop(), name="cloud-integrations")
    try:
        yield
    finally:
        attendance_task.cancel()
        cloud_automation_task.cancel()
        with suppress(asyncio.CancelledError):
            await attendance_task
        with suppress(asyncio.CancelledError):
            await cloud_automation_task


app = FastAPI(title="NMTPL Central Operations Platform", version="1.0.0-tiom2.1.0-field-hardening", lifespan=lifespan)


def legacy_access(request: Request, db=Depends(get_db)):
    user = get_user(db, request)
    require(user, admin=True)
    if request.method not in {'GET', 'HEAD'}:
        raise HTTPException(409, 'Legacy writes are disabled during the pilot. Use the migrated webapp.')


@app.middleware('http')
async def response_headers(request, call_next):
    response = await call_next(request)
    response.headers['X-Content-Type-Options'] = 'nosniff'
    response.headers['X-Frame-Options'] = 'DENY'
    response.headers['Referrer-Policy'] = 'same-origin'
    response.headers['Permissions-Policy'] = 'camera=(), microphone=(), geolocation=()'
    response.headers['Content-Security-Policy'] = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://commons.wikimedia.org https://upload.wikimedia.org https://*.googleusercontent.com https://*.gstatic.com; connect-src 'self'; frame-src https://www.google.com https://www.google.co.in; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"
    if request.url.scheme == 'https' or request.headers.get('x-forwarded-proto', '').split(',')[0].strip() == 'https':
        response.headers['Strict-Transport-Security'] = 'max-age=31536000; includeSubDomains'
    if (request.url.path.startswith('/api/') and not request.url.path.startswith('/api/volvo/map-tile/')) or request.url.path in {'/','/tiom','/central-control'} or request.url.path.startswith('/site/'):
        response.headers['Cache-Control'] = 'no-store'
    elif request.url.path.startswith('/static/'):
        # Static URLs are versioned with ?v= in the HTML, so cache aggressively on field devices.
        response.headers['Cache-Control'] = 'public, max-age=31536000, immutable' if request.url.query else 'public, max-age=300, must-revalidate'
    return response

from app.routers import volvo, automation, sync
app.include_router(volvo.router)
app.include_router(automation.router)
app.include_router(sync.router)
app.include_router(health.router)
app.include_router(webapp.router)
app.include_router(sites.router)
app.include_router(site_ops.router)
app.include_router(maintenance.router)
for router in (masters.router, production.router, hsd.router, reconciliation.router, dashboard.router, shift_control.router):
    app.include_router(router, dependencies=[Depends(legacy_access)])

STATIC = Path(__file__).resolve().parent / 'static'
app.mount('/static', StaticFiles(directory=STATIC), name='static')

@app.get("/")
def root():
    return FileResponse(STATIC / 'landing.html')


@app.get('/central-control')
def central_control():
    return FileResponse(STATIC / 'central.html')


@app.get("/tiom")
def tiom_app():
    return FileResponse(STATIC / 'index.html')


@app.get("/site/{site_id}")
def site_app(site_id: str):
    site_id = str(site_id or "").upper().strip()
    # TIOM is a dedicated application, not part of the generic SOCP/KOCP site shell.
    if site_id == "TIOM":
        return RedirectResponse("/tiom", status_code=307)
    if site_id not in {"SOCP", "KOCP"}:
        return RedirectResponse("/", status_code=307)
    return FileResponse(STATIC / 'site.html')


@app.get("/tiom/mechanical")
def tiom_mechanical_app():
    # Compatibility only: Mechanical is now an integrated tab inside /tiom.
    return RedirectResponse('/tiom', status_code=307)


@app.get("/site/{site_id}/mechanical")
def mechanical_app(site_id: str):
    # Compatibility only: site modules stay inside their ERP workspace.
    return RedirectResponse(f'/site/{site_id}', status_code=307)
